/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/LandingPage.tsx',
    './src/pages/MarketplacePage.tsx',
    './src/pages/CartPage.tsx',
    './src/pages/OEMPartsPage.tsx',
    './src/pages/SuppliersPage.tsx',
    './src/pages/LogisticsPage.tsx',
    './src/components/CatalogSearchBar.tsx',
  ],
  corePlugins: {
    // Disable preflight (CSS reset) — keeps existing ERP inline-style pages intact
    preflight: false,
  },
  theme: {
    extend: {
      colors: {
        'surface':                   '#fcf9f8',
        'surface-dim':               '#dcd9d9',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#f6f3f2',
        'surface-container':         '#f0eded',
        'surface-container-high':    '#eae7e7',
        'surface-container-highest': '#e5e2e1',
        'surface-variant':           '#e5e2e1',
        'on-surface':                '#1c1b1b',
        'on-surface-variant':        '#58413f',
        'outline':                   '#8b716e',
        'outline-variant':           '#dfbfbc',
        'primary':                   '#8b1e1e',
        'on-primary':                '#ffffff',
        'primary-container':         '#8b1e1e',
        'on-primary-container':      '#ff9d95',
        'primary-fixed':             '#ffdad6',
        'primary-fixed-dim':         '#ffb3ad',
        'on-primary-fixed':          '#410003',
        'on-primary-fixed-variant':  '#891c1d',
        'secondary':                 '#5d5f5b',
        'secondary-container':       '#e0e0db',
        'background':                '#fcf9f8',
        'on-background':             '#1c1b1b',
        'tertiary':                  '#313333',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#474949',
      },
      borderRadius: {
        'lg':  '8px',
        'xl':  '12px',
        'xxl': '16px',
        'full':'9999px',
      },
      spacing: {
        'xs':    '4px',
        'sm':    '8px',
        'md':    '12px',
        'lg':    '16px',
        'xl':    '24px',
        'xxl':   '32px',
        'huge':  '48px',
        'giant': '64px',
      },
      fontFamily: {
        'body-md':   ['Inter', 'sans-serif'],
        'title-lg':  ['Inter', 'sans-serif'],
        'label-md':  ['Inter', 'sans-serif'],
        'headline-md':['Poppins','sans-serif'],
        'display-lg':['Poppins','sans-serif'],
      },
      fontSize: {
        'display-lg':  ['48px',{ lineHeight:'1.2', letterSpacing:'-0.02em', fontWeight:'600' }],
        'headline-md': ['32px',{ lineHeight:'1.3', fontWeight:'600' }],
        'title-lg':    ['20px',{ lineHeight:'1.4', fontWeight:'600' }],
        'body-md':     ['16px',{ lineHeight:'1.6', fontWeight:'400' }],
        'label-md':    ['14px',{ lineHeight:'1.2', fontWeight:'500' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms')({ strategy: 'class' }),
  ],
}
